name: graceful-hammer
channels:
  - conda-forge
dependencies:
  - pandas
  - numpy
  - keras
  - openjdk
  - gcc_linux-64
  - gxx_linux-64
  - ruby=2.5.*
  - matplotlib
  - lxml
  - requests
  - scikit-learn
  - wget
  - prophet